version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`
      - npm run build-client
  post_build:
    commands:
      - echo Build Completed on `date`

artifacts:
  files:
    - '**/*'
